export const GETALLHASHTAG_INIT = 'GETALLHASHTAG_INIT';
export const GETALLHASHTAG_SUCCESS = 'GETALLHASHTAG_SUCCESS';
export const GETALLHASHTAG_ERROR = 'GETALLHASHTAG_ERROR';
export const CREAREHASHTAG_INIT = 'CREAREHASHTAG_INIT';
export const CREAREHASHTAG_SUCCESS = 'CREAREHASHTAG_SUCCESS';
export const CREAREHASHTAG_ERROR = 'CREAREHASHTAG_ERROR';